import type { AdminCompaniesResponse, AdminUsersResponse } from "@/types/admin";
import type { JobPostingStatus, PublicJobPosting } from "@/types/company-job-posting";
import type { InquiryListResponse } from "@/types/inquiry";
import type { ApplyJobResponse, CompanyApplicant, JobApplication } from "@/types/jobApplication";
import type { JobDetailResponse } from "@/types/job";
import type { TalentDetailResponse } from "@/types/talent";
import type { TalentListItem } from "@/lib/api/talents";

export const DEMO_ROLE_NOW = "2026-05-12T00:00:00.000Z";
const DEMO_PROFILE_IMAGE_URL = "/demo/profile-demo.png";
const DEMO_HONG_PORTFOLIO_URL = "/demo/mock_portfolio_frontend_honggildong.pdf";
const DEMO_TEST_PORTFOLIO_URL = "/demo/mock_portfolio_frontend_test.pdf";

export const demoPublicJobs: PublicJobPosting[] = [
  {
    jobPostingId: 9001,
    title: "Next.js 프론트엔드 개발자",
    companyName: "데모커머스",
    jobGroupName: "개발",
    jobRoleName: "프론트엔드",
    employmentType: "FULL_TIME",
    workplaceShort: "서울 강남",
    thumbnailImageKey: null,
    thumbnailImageUrl: "/demo/demo-cover.png",
    publishedAt: DEMO_ROLE_NOW,
  },
  {
    jobPostingId: 9002,
    title: "React Product Engineer",
    companyName: "모크테크",
    jobGroupName: "개발",
    jobRoleName: "프론트엔드",
    employmentType: "INTERN",
    workplaceShort: "서울 성수",
    thumbnailImageKey: null,
    thumbnailImageUrl: "/demo/demo-cover2.png",
    publishedAt: DEMO_ROLE_NOW,
  },
  {
    jobPostingId: 9003,
    title: "디자인 시스템 프론트엔드 개발자",
    companyName: "데모커머스",
    jobGroupName: "개발",
    jobRoleName: "프론트엔드",
    employmentType: "FULL_TIME",
    workplaceShort: "서울 강남",
    thumbnailImageKey: null,
    thumbnailImageUrl: "/demo/demo-cover.png",
    publishedAt: DEMO_ROLE_NOW,
  },
  {
    jobPostingId: 9004,
    title: "백엔드 플랫폼 엔지니어",
    companyName: "모크테크",
    jobGroupName: "개발",
    jobRoleName: "백엔드",
    employmentType: "FULL_TIME",
    workplaceShort: "서울 성수",
    thumbnailImageKey: null,
    thumbnailImageUrl: "/demo/demo-cover2.png",
    publishedAt: DEMO_ROLE_NOW,
  },
  {
    jobPostingId: 9005,
    title: "프로덕트 UX/UI 디자이너",
    companyName: "데모커머스",
    jobGroupName: "디자인",
    jobRoleName: "UX/UI",
    employmentType: "FULL_TIME",
    workplaceShort: "서울 강남",
    thumbnailImageKey: null,
    thumbnailImageUrl: "/demo/demo-cover.png",
    publishedAt: DEMO_ROLE_NOW,
  },
  {
    jobPostingId: 9006,
    title: "그로스 마케팅 매니저",
    companyName: "모크테크",
    jobGroupName: "마케팅",
    jobRoleName: "그로스 마케팅",
    employmentType: "FULL_TIME",
    workplaceShort: "서울 성수",
    thumbnailImageKey: null,
    thumbnailImageUrl: "/demo/demo-cover2.png",
    publishedAt: DEMO_ROLE_NOW,
  },
];

export const demoJobDetails: JobDetailResponse[] = [
  {
    jobPostingId: 9001,
    title: "Next.js 프론트엔드 개발자",
    employmentType: "FULL_TIME",
    jobDescription: "LionConnect 데모에서 공개 채용 상세 화면을 확인하기 위한 공고입니다.",
    mainTasks: "Next.js App Router 기반 화면 개발, API 상태 관리, 폼 UX 개선",
    requirements: "React, TypeScript, TanStack Query 사용 경험",
    preferred: "접근성과 테스트 자동화에 관심이 있는 분",
    benefits: "자율 출퇴근, 코드 리뷰 문화, 포트폴리오 성장 지원",
    hiringProcess: "서류 검토 -> 인터뷰 -> 최종 합류",
    workplace: "서울특별시 강남구 데모로 19",
    companyName: "데모커머스",
    courseName: "멋쟁이사자처럼 프론트엔드 스쿨",
    courseGeneration: 13,
    jobGroupName: "개발",
    jobRoleId: 1,
    jobRoleName: "프론트엔드",
    publishedAt: DEMO_ROLE_NOW,
    images: [
      {
        objectKey: "demo/demo-cover.png",
        contentType: "image/png",
        fileSize: 1024,
        originalFilename: "demo-cover.png",
        sortOrder: 1,
        url: "/demo/demo-cover.png",
        fileUrl: "/demo/demo-cover.png",
      },
    ],
    myJobApplicationId: 8001,
    myJobApplicationStatus: "APPLIED",
    applied: true,
  },
  {
    jobPostingId: 9002,
    title: "React Product Engineer",
    employmentType: "INTERN",
    jobDescription: "제품 실험과 빠른 화면 개선을 함께 경험하는 인턴 포지션입니다.",
    mainTasks: "컴포넌트 설계, 성능 점검, 대시보드 개선",
    requirements: "React 기본기와 Git 협업 경험",
    preferred: "폼/상태 관리 경험",
    benefits: "멘토링, 실무 프로젝트 참여",
    hiringProcess: "서류 검토 -> 과제 -> 인터뷰",
    workplace: "서울특별시 성동구 데모길 9",
    companyName: "모크테크",
    courseName: "멋쟁이사자처럼 프론트엔드 스쿨",
    courseGeneration: 13,
    jobGroupName: "개발",
    jobRoleId: 1,
    jobRoleName: "프론트엔드",
    publishedAt: DEMO_ROLE_NOW,
    images: [
      {
        objectKey: "demo/demo-cover2.png",
        contentType: "image/png",
        fileSize: 1024,
        originalFilename: "demo-cover2.png",
        sortOrder: 1,
        url: "/demo/demo-cover2.png",
        fileUrl: "/demo/demo-cover2.png",
      },
    ],
    myJobApplicationId: null,
    myJobApplicationStatus: null,
    applied: false,
  },
  {
    jobPostingId: 9003,
    title: "디자인 시스템 프론트엔드 개발자",
    employmentType: "FULL_TIME",
    jobDescription:
      "아직 게시하지 않은 채용공고 예시입니다. 게시하기 전에는 인재 랜딩 페이지에 노출되지 않습니다.",
    mainTasks: "공통 컴포넌트 설계, 디자인 토큰 관리, 사용 가이드 문서화",
    requirements: "React, TypeScript 실무 경험",
    preferred: "디자인 시스템 구축 또는 운영 경험",
    benefits: "유연근무, 교육비 지원, 코드 리뷰 문화",
    hiringProcess: "서류 검토 -> 인터뷰 -> 최종 합류",
    workplace: "서울특별시 강남구 데모로 19",
    companyName: "데모커머스",
    courseName: "멋쟁이사자처럼 프론트엔드 스쿨",
    courseGeneration: 13,
    jobGroupName: "개발",
    jobRoleId: 1,
    jobRoleName: "프론트엔드",
    publishedAt: DEMO_ROLE_NOW,
    images: [
      {
        objectKey: "demo/demo-cover.png",
        contentType: "image/png",
        fileSize: 1024,
        originalFilename: "demo-cover.png",
        sortOrder: 1,
        url: "/demo/demo-cover.png",
        fileUrl: "/demo/demo-cover.png",
      },
    ],
    myJobApplicationId: null,
    myJobApplicationStatus: null,
    applied: false,
  },
  {
    jobPostingId: 9004,
    title: "백엔드 플랫폼 엔지니어",
    employmentType: "FULL_TIME",
    jobDescription: "안정적인 API 플랫폼과 데이터 파이프라인을 함께 만드는 포지션입니다.",
    mainTasks: "REST API 설계, 데이터베이스 모델링, 성능 모니터링",
    requirements: "Java 또는 Kotlin, Spring 기반 백엔드 개발 경험",
    preferred: "대용량 트래픽 처리, 클라우드 인프라 운영 경험",
    benefits: "자율 출퇴근, 도서 구입 지원, 컨퍼런스 참가비 지원",
    hiringProcess: "서류 검토 -> 기술 인터뷰 -> 최종 합류",
    workplace: "서울특별시 성동구 데모길 9",
    companyName: "모크테크",
    courseName: "멋쟁이사자처럼 백엔드 스쿨",
    courseGeneration: 13,
    jobGroupName: "개발",
    jobRoleId: 2,
    jobRoleName: "백엔드",
    publishedAt: DEMO_ROLE_NOW,
    images: [
      {
        objectKey: "demo/demo-cover2.png",
        contentType: "image/png",
        fileSize: 1024,
        originalFilename: "demo-cover2.png",
        sortOrder: 1,
        url: "/demo/demo-cover2.png",
        fileUrl: "/demo/demo-cover2.png",
      },
    ],
    myJobApplicationId: null,
    myJobApplicationStatus: null,
    applied: false,
  },
  {
    jobPostingId: 9005,
    title: "프로덕트 UX/UI 디자이너",
    employmentType: "FULL_TIME",
    jobDescription: "사용자 리서치부터 화면 설계까지 제품 경험 전반을 담당합니다.",
    mainTasks: "사용자 흐름 설계, 와이어프레임/프로토타입 제작, 디자인 QA",
    requirements: "Figma 활용 능력과 UX 설계 경험",
    preferred: "디자인 시스템 운영, 프론트엔드 협업 경험",
    benefits: "유연근무, 디자인 툴 라이선스 지원, 워크숍 지원",
    hiringProcess: "서류 검토 -> 포트폴리오 인터뷰 -> 최종 합류",
    workplace: "서울특별시 강남구 데모로 19",
    companyName: "데모커머스",
    courseName: "멋쟁이사자처럼 디자인 스쿨",
    courseGeneration: 13,
    jobGroupName: "디자인",
    jobRoleId: 7,
    jobRoleName: "UX/UI",
    publishedAt: DEMO_ROLE_NOW,
    images: [
      {
        objectKey: "demo/demo-cover.png",
        contentType: "image/png",
        fileSize: 1024,
        originalFilename: "demo-cover.png",
        sortOrder: 1,
        url: "/demo/demo-cover.png",
        fileUrl: "/demo/demo-cover.png",
      },
    ],
    myJobApplicationId: null,
    myJobApplicationStatus: null,
    applied: false,
  },
  {
    jobPostingId: 9006,
    title: "그로스 마케팅 매니저",
    employmentType: "FULL_TIME",
    jobDescription: "데이터 기반으로 사용자 유입과 전환을 키우는 그로스 포지션입니다.",
    mainTasks: "퍼널 분석, 광고/콘텐츠 캠페인 운영, A/B 테스트 설계",
    requirements: "퍼포먼스 마케팅 또는 그로스 실무 경험",
    preferred: "GA4/Amplitude 등 데이터 분석 도구 활용 경험",
    benefits: "성과 인센티브, 자율 출퇴근, 교육비 지원",
    hiringProcess: "서류 검토 -> 실무 인터뷰 -> 최종 합류",
    workplace: "서울특별시 성동구 데모길 9",
    companyName: "모크테크",
    courseName: "멋쟁이사자처럼 마케팅 스쿨",
    courseGeneration: 13,
    jobGroupName: "마케팅",
    jobRoleId: 9,
    jobRoleName: "그로스 마케팅",
    publishedAt: DEMO_ROLE_NOW,
    images: [
      {
        objectKey: "demo/demo-cover2.png",
        contentType: "image/png",
        fileSize: 1024,
        originalFilename: "demo-cover2.png",
        sortOrder: 1,
        url: "/demo/demo-cover2.png",
        fileUrl: "/demo/demo-cover2.png",
      },
    ],
    myJobApplicationId: null,
    myJobApplicationStatus: null,
    applied: false,
  },
];

export const demoTalentList: TalentListItem[] = [
  {
    id: 1,
    name: "홍길동",
    introduction: "Next.js와 TypeScript로 실제 서비스형 화면을 안정적으로 구현합니다.",
    email: "talent.demo@lionconnect.test",
    phoneNumber: "010-0000-0001",
    experiences: ["부트캠프 경험자", "창업 경험자"],
    tendencies: ["문제 해결", "협업 지향"],
    education: {
      schoolName: "라이언대학교",
      major: "컴퓨터공학",
    },
    jobRoles: ["프론트엔드"],
    skills: ["React", "Next.js", "TypeScript"],
    thumbnailUrl: DEMO_PROFILE_IMAGE_URL,
    workDrivenLevel: 4,
  },
  {
    id: 2,
    name: "데모 백엔드 인재",
    introduction: "Spring 기반 API와 데이터 모델링으로 안정적인 서버를 설계합니다.",
    email: "talent.backend@lionconnect.test",
    phoneNumber: "010-0000-0011",
    experiences: ["부트캠프 경험자"],
    tendencies: ["꼼꼼함", "성능 지향"],
    education: {
      schoolName: "라이언대학교",
      major: "소프트웨어공학",
    },
    jobRoles: ["백엔드"],
    skills: ["Java", "Spring", "MySQL"],
    thumbnailUrl: "/images/default-profile.png",
    workDrivenLevel: 4,
  },
  {
    id: 3,
    name: "데모 디자인 인재",
    introduction: "사용자 리서치 기반으로 직관적인 제품 경험을 설계합니다.",
    email: "talent.design@lionconnect.test",
    phoneNumber: "010-0000-0012",
    experiences: ["창업 경험자"],
    tendencies: ["사용자 중심", "협업 지향"],
    education: {
      schoolName: "라이언대학교",
      major: "산업디자인",
    },
    jobRoles: ["UX/UI"],
    skills: ["Figma", "Prototyping", "Design System"],
    thumbnailUrl: "/images/default-profile.png",
    workDrivenLevel: 3,
  },
];

export const demoTalentDetails: TalentDetailResponse[] = [
  {
    id: 1,
    name: "홍길동",
    title: "프론트엔드 포트폴리오 이력서",
    introduction: "Next.js와 TypeScript로 실제 서비스형 화면을 안정적으로 구현합니다.",
    email: "talent.demo@lionconnect.test",
    phoneNumber: "010-0000-0001",
    jobRoles: ["프론트엔드"],
    tendencies: ["문제 해결", "협업 지향"],
    experiences: ["부트캠프 경험자", "창업 경험자"],
    skills: ["React", "Next.js", "TypeScript"],
    languages: ["TOEIC Speaking IH"],
    thumbnailUrl: DEMO_PROFILE_IMAGE_URL,
    portfolioUrl: DEMO_HONG_PORTFOLIO_URL,
    externalLink: "https://github.com/ChoiMHMH/lion-connect-demo",
    externalLinks: ["https://github.com/ChoiMHMH/lion-connect-demo"],
    storageUrl: DEMO_HONG_PORTFOLIO_URL,
    likelionCertified: true,
    updatedAt: DEMO_ROLE_NOW,
    workExperiences: [
      {
        id: 201,
        companyName: "데모랩",
        department: "프로덕트팀",
        position: "Frontend Intern",
        startDate: "2024-03-01",
        endDate: "2024-08-01",
        isCurrent: false,
        description: "채용 관리 화면의 필터링과 상세 조회 UI를 구현했습니다.",
        createdAt: DEMO_ROLE_NOW,
        updatedAt: DEMO_ROLE_NOW,
      },
    ],
    educations: [
      {
        id: 101,
        schoolName: "라이언대학교",
        major: "컴퓨터공학",
        status: "GRADUATED",
        startDate: "2020-03-01",
        endDate: "2024-02-01",
        degree: "학사",
        description: "웹 서비스 설계와 사용자 인터페이스 과목을 중심으로 학습했습니다.",
        createdAt: DEMO_ROLE_NOW,
        updatedAt: DEMO_ROLE_NOW,
      },
    ],
    certifications: [
      {
        id: 401,
        name: "정보처리기사",
        issuer: "한국산업인력공단",
        issueDate: "2025-06-01",
        createdAt: DEMO_ROLE_NOW,
        updatedAt: DEMO_ROLE_NOW,
      },
    ],
    awards: [
      {
        id: 501,
        title: "교내 웹 서비스 해커톤 우수상",
        organization: "라이언대학교",
        awardDate: "2025-08-01",
        description: "사용자 피드백 기반 대시보드 개선안을 구현했습니다.",
        createdAt: DEMO_ROLE_NOW,
        updatedAt: DEMO_ROLE_NOW,
      },
    ],
    languageDetails: [
      {
        id: 301,
        languageName: "TOEIC Speaking",
        level: "IH",
        issueDate: "2025-01-01",
        createdAt: DEMO_ROLE_NOW,
        updatedAt: DEMO_ROLE_NOW,
      },
    ],
    workDrivenLevel: 4,
  },
  {
    id: 2,
    name: "데모 백엔드 인재",
    title: "백엔드 엔지니어 포트폴리오 이력서",
    introduction: "Spring 기반 API와 데이터 모델링으로 안정적인 서버를 설계합니다.",
    email: "talent.backend@lionconnect.test",
    phoneNumber: "010-0000-0011",
    jobRoles: ["백엔드"],
    tendencies: ["꼼꼼함", "성능 지향"],
    experiences: ["부트캠프 경험자"],
    skills: ["Java", "Spring", "MySQL"],
    languages: ["TOEIC 900"],
    thumbnailUrl: "/images/default-profile.png",
    portfolioUrl: DEMO_TEST_PORTFOLIO_URL,
    externalLink: "https://github.com/ChoiMHMH/lion-connect-demo",
    externalLinks: ["https://github.com/ChoiMHMH/lion-connect-demo"],
    storageUrl: DEMO_TEST_PORTFOLIO_URL,
    likelionCertified: true,
    updatedAt: DEMO_ROLE_NOW,
    workExperiences: [
      {
        id: 211,
        companyName: "데모랩",
        department: "플랫폼팀",
        position: "Backend Intern",
        startDate: "2024-03-01",
        endDate: "2024-08-01",
        isCurrent: false,
        description: "공고/지원 도메인 API와 배치 작업을 구현했습니다.",
        createdAt: DEMO_ROLE_NOW,
        updatedAt: DEMO_ROLE_NOW,
      },
    ],
    educations: [
      {
        id: 111,
        schoolName: "라이언대학교",
        major: "소프트웨어공학",
        status: "GRADUATED",
        startDate: "2020-03-01",
        endDate: "2024-02-01",
        degree: "학사",
        description: "데이터베이스와 분산 시스템 과목을 중심으로 학습했습니다.",
        createdAt: DEMO_ROLE_NOW,
        updatedAt: DEMO_ROLE_NOW,
      },
    ],
    certifications: [
      {
        id: 411,
        name: "SQLD",
        issuer: "한국데이터산업진흥원",
        issueDate: "2025-05-01",
        createdAt: DEMO_ROLE_NOW,
        updatedAt: DEMO_ROLE_NOW,
      },
    ],
    awards: [],
    languageDetails: [
      {
        id: 311,
        languageName: "TOEIC",
        level: "900",
        issueDate: "2025-01-01",
        createdAt: DEMO_ROLE_NOW,
        updatedAt: DEMO_ROLE_NOW,
      },
    ],
    workDrivenLevel: 4,
  },
  {
    id: 3,
    name: "데모 디자인 인재",
    title: "UX/UI 디자이너 포트폴리오 이력서",
    introduction: "사용자 리서치 기반으로 직관적인 제품 경험을 설계합니다.",
    email: "talent.design@lionconnect.test",
    phoneNumber: "010-0000-0012",
    jobRoles: ["UX/UI"],
    tendencies: ["사용자 중심", "협업 지향"],
    experiences: ["창업 경험자"],
    skills: ["Figma", "Prototyping", "Design System"],
    languages: ["OPIc IM2"],
    thumbnailUrl: "/images/default-profile.png",
    portfolioUrl: DEMO_TEST_PORTFOLIO_URL,
    externalLink: "https://github.com/ChoiMHMH/lion-connect-demo",
    externalLinks: ["https://github.com/ChoiMHMH/lion-connect-demo"],
    storageUrl: DEMO_TEST_PORTFOLIO_URL,
    likelionCertified: true,
    updatedAt: DEMO_ROLE_NOW,
    workExperiences: [
      {
        id: 221,
        companyName: "데모스튜디오",
        department: "프로덕트디자인팀",
        position: "Product Designer Intern",
        startDate: "2024-03-01",
        endDate: "2024-08-01",
        isCurrent: false,
        description: "채용 대시보드의 정보 구조와 인터랙션을 재설계했습니다.",
        createdAt: DEMO_ROLE_NOW,
        updatedAt: DEMO_ROLE_NOW,
      },
    ],
    educations: [
      {
        id: 121,
        schoolName: "라이언대학교",
        major: "산업디자인",
        status: "GRADUATED",
        startDate: "2020-03-01",
        endDate: "2024-02-01",
        degree: "학사",
        description: "사용자 경험 설계와 시각 디자인 과목을 중심으로 학습했습니다.",
        createdAt: DEMO_ROLE_NOW,
        updatedAt: DEMO_ROLE_NOW,
      },
    ],
    certifications: [],
    awards: [
      {
        id: 511,
        title: "교내 UX 공모전 최우수상",
        organization: "라이언대학교",
        awardDate: "2025-08-01",
        description: "접근성을 고려한 채용 서비스 리디자인안을 제안했습니다.",
        createdAt: DEMO_ROLE_NOW,
        updatedAt: DEMO_ROLE_NOW,
      },
    ],
    languageDetails: [
      {
        id: 321,
        languageName: "OPIc",
        level: "IM2",
        issueDate: "2025-01-01",
        createdAt: DEMO_ROLE_NOW,
        updatedAt: DEMO_ROLE_NOW,
      },
    ],
    workDrivenLevel: 3,
  },
];

export const demoApplications: JobApplication[] = [
  {
    jobApplicationId: 8001,
    jobPostingId: 9001,
    status: "APPLIED",
    appliedAt: DEMO_ROLE_NOW,
    canceledAt: null,
    companyName: "데모커머스",
    jobPostingTitle: "Next.js 프론트엔드 개발자",
    jobGroupName: "개발",
    jobRoleName: "프론트엔드",
  },
];

/**
 * 데모 전용 지원자 타입.
 * 실제 API는 `/company/job-postings/{jobId}/applications` 처럼 URL로 공고가 결정되어
 * 응답에 jobPostingId가 없으므로, 공용 CompanyApplicant는 그대로 두고
 * 데모 store에서 공고별 필터링을 위해서만 jobPostingId를 덧붙인다.
 */
export type DemoApplicant = CompanyApplicant & { jobPostingId: number };

export const demoApplicants: DemoApplicant[] = [
  {
    jobPostingId: 9001,
    applicantName: "홍길동",
    jobGroupName: "개발",
    jobRoleName: "프론트엔드",
    appliedAt: DEMO_ROLE_NOW,
    applicationStatus: "APPLIED",
    talentProfileId: 1,
    talentProfileTitle: "프론트엔드 포트폴리오 이력서",
  },
];

export const demoAdminUsers: AdminUsersResponse["content"] = [
  {
    id: 1001,
    name: "홍길동",
    phoneNumber: "010-0000-0001",
    email: "talent.demo@lionconnect.test",
    joinedAt: DEMO_ROLE_NOW,
    roles: ["JOINEDUSER"],
    locked: false,
    courseName: "프론트엔드 스쿨",
    courseGeneration: 13,
  },
  {
    id: 1002,
    name: "데모 관리자",
    phoneNumber: "010-0000-0003",
    email: "admin.demo@lionconnect.test",
    joinedAt: DEMO_ROLE_NOW,
    roles: ["ADMIN"],
    locked: false,
  },
];

export const demoAdminCompanies: AdminCompaniesResponse["content"] = [
  {
    id: 2001,
    name: "기업 담당자",
    companyName: "데모커머스",
    phoneNumber: "010-0000-0002",
    email: "company.demo@lionconnect.test",
    joinedAt: DEMO_ROLE_NOW,
    roles: ["JOINEDCOMPANY"],
    companyLocked: false,
  },
];

export const demoInquiries: InquiryListResponse["content"] = [
  {
    id: 7001,
    profileId: 1,
    profileName: "홍길동",
    profileStorageUrl: DEMO_HONG_PORTFOLIO_URL,
    companyName: "데모파트너스",
    contactPerson: "채용 담당자",
    department: "인재영입팀",
    position: "매니저",
    email: "partner.demo@lionconnect.test",
    phoneNumber: "010-0000-0004",
    content: "프론트엔드 포지션 인터뷰를 제안하고 싶습니다.",
    privacyPolicyAgreed: true,
    status: "NEW",
    createdAt: DEMO_ROLE_NOW,
    updatedAt: DEMO_ROLE_NOW,
  },
];

export type DemoRoleSeed = {
  jobs: PublicJobPosting[];
  jobDetails: JobDetailResponse[];
  talents: TalentListItem[];
  talentDetails: TalentDetailResponse[];
  applications: JobApplication[];
  applicants: DemoApplicant[];
  adminUsers: AdminUsersResponse["content"];
  adminCompanies: AdminCompaniesResponse["content"];
  inquiries: InquiryListResponse["content"];
  jobStatuses: Record<number, JobPostingStatus>;
  nextApplicationId: number;
};

export const demoRoleSeed: DemoRoleSeed = {
  jobs: demoPublicJobs,
  jobDetails: demoJobDetails,
  talents: demoTalentList,
  talentDetails: demoTalentDetails,
  applications: demoApplications,
  applicants: demoApplicants,
  adminUsers: demoAdminUsers,
  adminCompanies: demoAdminCompanies,
  inquiries: demoInquiries,
  jobStatuses: {
    9001: "PUBLISHED",
    9002: "PUBLISHED",
    9003: "DRAFT",
    9004: "PUBLISHED",
    9005: "PUBLISHED",
    9006: "PUBLISHED",
  },
  nextApplicationId: 8002,
};

export type { ApplyJobResponse };
